const fs = require('fs');

// We have two options for the Service Worker:
// Option A: Let Vite generate 'sw.js' using 'generateSW', but it will OVERWRITE 'push-sw.js' logic if they conflict on scope.
// Option B: Switch VitePWA to 'injectManifest' mode and use 'public/push-sw.js' as the source.

let viteConfig = fs.readFileSync('vite.config.ts', 'utf8');

// Let's use injectManifest to merge both!
viteConfig = viteConfig.replace(`registerType: 'autoUpdate',`, `registerType: 'autoUpdate',\n        strategies: 'injectManifest',\n        srcDir: 'public',\n        filename: 'push-sw.js',`);

fs.writeFileSync('vite.config.ts', viteConfig, 'utf8');

let pushSw = fs.readFileSync('public/push-sw.js', 'utf8');
const injection = `
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Offline Fallback for SPA (index.html)
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'navigation-cache',
    })
  )
);

// Cache Google Fonts
registerRoute(
  /^https:\\/\\/fonts\\.googleapis\\.com\\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 })
    ]
  })
);

// Cache API Rates (Network First)
registerRoute(
  /^\\/api\\/rates/i,
  new NetworkFirst({
    cacheName: 'rates-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({ maxEntries: 5, maxAgeSeconds: 60 * 60 })
    ]
  })
);

`;

if (!pushSw.includes('workbox-precaching')) {
  fs.writeFileSync('public/push-sw.js', injection + pushSw, 'utf8');
}

console.log('Switched to injectManifest and added Workbox caching to push-sw.js');
